# Build settings
markdown: kramdown

# Site settings
title: Project-Cylon
description: Don't coding, just testing.

url: http://project-cylon.io # the base hostname & protocol for your site
baseurl: /project-cylon # the subpath of your site, e.g. /blog/

# Custom variables
version: 1.1.10
github: https://github.com/gigapixel/project-cylon
